# Baseimage to build NPM related packages (stage 1) (big image)

FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .




#Base image to run the app only (stage 2) (small image)


FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app .


EXPOSE 5173

CMD ["npm", "run", "dev"]
